### ISSUE TITLE
Add option for `CronJob`

### ISSUE THREAD

**Issue by iameskild** [kbatch-dev/kbatch#38]
@TomAugspurger @yuvipanda @arokem 

Having an option to specify a schedule for your job is a feature I think kbatch and it's potential users might benefit from. I've taken a stab at some basic implementation which you can find here: [iameskild/cronjob branch diff](https://github.com/kbatch-dev/kbatch/compare/main...iameskild:cronjob).

This implementation assumes that the underlying pod-spec template for both `Job` and `CronJob` resources are the same. This makes it simple to fold these pod-specs templates into different models, `V1Job` and `V1CronJob` respectively. This does ultimately abstracts away the difference between the two different models, at least from the user perspective: "they are all jobs, specify a schedule if you want to".

To specify that you want to run a cronjob instead of a job, you can simply specify a `--schedule="* * * * *"` from the CLI or config file. I believe this is all that we might need from the user in order to create a cronjob versus a regular job.

The diff reference above has a handful of outstanding to-do's / questions before it's ready to go.
- [ ] how does a user stop the cron job? 
 - perhaps there should be a default number of successfully completed jobs after which the cronjob is terminated, something the user can specify 
- [ ] when the jobs are listed, should there be an additional column for the schedule? or a separate cli command altogether?

This is my attempt at starting a discussion on around this topic but if and when ready, I'd be happy to open a PR and see it through. 

Thanks again for considering this feature request :)

cc @Adam-D-Lewis @costrouc

**Comment by TomAugspurger** [comment]
Thanks for opening this up @iameskild, and apologies for the delay. Adding support for CronJobs is totally in scope, and your implementation seems pretty reasonable. I'd say make a PR whenever you're ready.

**Comment by dharhas** [comment]
> how does a user stop the cron job?

something like `kbatch job --schedule cancel "<job-id>"` or similar

> when the jobs are listed, should there be an additional column for the schedule? or a separate cli command altogether?

I would say additional column that shows schedule

**Comment by dharhas** [comment]
There is a different between removing a stuck/bad job and removing it from the schedule. Not quite sure how you make the different clear via the cli options.

**Comment by iameskild** [comment]
Closed by #40
