### ISSUE TITLE
Cut new release of kbatch/kbatch-proxy

### ISSUE THREAD

**Issue by iameskild** [kbatch-dev/kbatch#41]
To take advantage of the added CronJob support, it would be great to cut a new release (once #40 is merged). 
Perhaps version `0.4.0`?

@TomAugspurger I obviously more than happy to handle this but I just wanted to double check to see if you had any input or perhaps a checklist I could follow?

**Comment by TomAugspurger** [comment]
I don't really have a checklist. Here's the start of one (from memory, so it might have gaps).

1. Draft a release at https://github.com/kbatch-dev/kbatch/releases. Next one would be 0.4.0 likely. That runs https://github.com/kbatch-dev/kbatch/blob/main/.github/workflows/publish-image.yaml, which should
    - Publish a container image to GitHub container registry
    - Publish kbatch and kbatch-proxy python libraries to PyPI (GitHub has a token to push there)
2. Publish a release at https://github.com/kbatch-dev/helm-chart (I can add you as a contributor). I think that automatically publishes to gh-pages at https://kbatch-dev.github.io/helm-chart/, but I might be wrong. I've struggled with this portion so if you have any interest in improving that workflow I'd be happy to see it.

**Comment by iameskild** [comment]
Thanks @TomAugspurger! I will have a closer look today but this sounds pretty reasonable to me. I'm also happy to be added as a contributor to the `helm-chart` repo if you are :)

**Comment by iameskild** [comment]
Hi @TomAugspurger, I've had a look at the gh actions you references and it seems like your checklist captures it all. I was thinking of going through the flow once, releasing `v0.4.0rc1` to test the process. I'll open a PR to formally document the process either way. 

Would it still be possible to be added as a contributor in the `helm-chart` repo? Thanks again!

**Comment by TomAugspurger** [comment]
Invite sent for the helm-chart repo.
