### ISSUE TITLE
authorization scopes, jupyterhub version support

### ISSUE THREAD

**Issue by minrk** [kbatch-dev/kbatch#69]
What is the target jupyterhub versions do you want to support?

Right now, kbatch_proxy uses JupyterHub 1.0-style auth where any authenticated user/token is fully authorized to use kbatch. Starting with JupyterHub 2, access would typically be governed by a scope like `access:services!service=kbatch-proxy` . The shared `jupyterhub-services` cookie was also removed in JupyterHub 2. HubAuth typically derives the required scope from $JUPYTERHUB_SERVICE_NAME.

Choices:

- Continue supporting JupyterHub 1 - make all new auth optional
- Require at least JupyterHub 2 (2021)  - can remove cookie auth, assume scopes are defined
- Require at least JupyterHub 3 (2022) would simplify implementation a tiny bit, as some relevant APIs were renamed.
 
Notably, this only affects the version of JupyterHub _in the kube-proxy environment_. Running with JupyterHub 5 in kube-proxy can still  work if the Hub is using JupyterHub 2.

When implementing scoped auth, there is a choice for implementing the scope check:

- Require scopes by default, which is backward-incompatible in that:
  - $JUPYTERHUB_SERVICE_NAME and/or $JUPYTERHUB_OAUTH_ACCESS_SCOPES become required environment variables
  - not all tokens will grant access to the service (e.g. the default $JUPYTERHUB_API_TOKEN would _not_ have access anymore without admin configuration)
- Backward-compatible by default - all authenticated users have access if no scopes are provided (less safe, config mistakes lead to unintended execute permissions)

I can do any of these, but I don't want to dictate the support range or backward-compatibility for a project I'm just starting to contribute to.

If I were to choose myself, I would pick:

- require JupyterHub >=3
- refuse to start if access scopes cannot be deduced (seems safest, matches current standard practice for jupyterhub services)

**Comment by TomAugspurger** [comment]
cc @iameskild, IIUC nebari isn't using kbatch anymore correct?

I'm also not aware of any deployments.

So I'd say go for requiring JupyterHub>=3.

**Comment by iameskild** [comment]
@minrk @TomAugspurger 

That is correct!

cc @viniciusdc @Adam-D-Lewis

**Comment by minrk** [comment]
#70 implements JupyterHub scope-based auth, and will fail if it cannot determine the required scopes (i.e. neither `$JUPYTERHUB_SERVICE_NAME` nor `$JUPYTERHUB_OAUTH_ACCESS_SCOPES` are defined).
